-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "2204x449", scale = 1 })
hl.monitor({ output = "DP-1", mode = "2560x1080@60.000", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-2", mode = "1920x1080@144.000", position = "0x1080", scale = 1, vrr = 0 })
hl.monitor({ output = "eDP-1", mode = "2880x1800@120.000", position = "1920x0", scale = 2, vrr = 0 })
