-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "3062x835", scale = 1 })
hl.monitor({ output = "desc:Samsung Display Corp. 0x419D", mode = "2880x1800@60.001", position = "2560x180", scale = 2 })
hl.monitor({ output = "desc:GWD ARZOPA 0x64630209", mode = "1920x1080@144.000", position = "640x1080", scale = 1 })
hl.monitor({ output = "desc:LG Electronics 25UM58G 0x01010101", mode = "720x400@70.082", position = "1121x680", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "2880x1800@60.001", position = "2560x180", scale = 2, vrr = 0 })
hl.monitor({ output = "DP-1", mode = "2560x1080@60.000", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-2", mode = "1920x1080@144.000", position = "369x1080", scale = 1, vrr = 0 })
