cursor #e2e2e2
cursor_text_color #cfc4c5

foreground            #e2e2e2
background            #131313
selection_foreground  #303030
selection_background  #c6c6c6
url_color             #c6c6c6

color0   #131313
color1   #e36666
color2   #78c663
color3   #f7dd6f
color4   #bcbcbc
color5   #5b5b5b
color6   #c6c6c6
color7   #cfc3c3
color8   #484040
color9   #ff9f9f
color10  #aced9a
color11  #ffeda5
color12  #d9d9d9
color13  #ffffff
color14  #ffffff
color15  #fff8f8
