#
# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

CONFIG_PATH=~/Projects/dotfiles

set -o emacs

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim=nvim

PATH=$PATH:~/.local/bin
source ${CONFIG_PATH}/extra-path

function create_ramdisk() {
    mkdir -p ~/ramdisk
    sudo mount -t tmpfs -o size=1G tmpfs ~/ramdisk
}

function config_ssh_auth() {
    unset SSH_AUTH_SOCK
    export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
    gpgconf --launc gpg-agent
}
config_ssh_auth

bind '"\C-f":"tmux-sessionizer\n"'

export XCOMPOSEFILE=$HOME/.XCompose

function g() {
	local encoded=$(echo $@ | jq -sRr @uri)
	xdg-open https://www.google.com/search?q=$encoded
	hyprctl dispatch workspace 1
}

function open_crypt_nb() {
	sudo ykfde-open -d /dev/nvme0n1p8 -n cryptdados
	sudo mount /dev/mapper/cryptdados /mnt/dados
}

function open_crypt() {
	sudo cryptsetup luksOpen /dev/sda1 cryptpen
	sudo mount /dev/mapper/cryptpen /mnt/dados
}

function close_crypt() {
	sudo umount /mnt/dados
	sudo cryptsetup close cryptpen
}

export EDITOR=nvim
export VISUAL=nvim

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/caio/.lmstudio/bin"
# End of LM Studio CLI section

export DBX_SKIP_WORKDIR=1
